name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_DEMO_CREDENTIAL }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Autheticae Google cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_DEMO_CREDENTIAL }}

      - name: Set up google cloud sdk
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform 
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform 
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform 
          terraform apply -auto-approve
